config/routes.rb
Rails.application.routes.draw do
  
  resources  :reviews

  root "reviews#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord

    geocoded_by :address
    after_validation :geocode


    validates :title, { presence: true }
    validates :body, length: { minimum:10 }
    validates :score, numericality: { only_integer: true, greater_that_or_equal_to: 0, less_than_or_equal_to: 10 }
    validates :restaurant, presence: true
    validates :price, numericality: { only_integer: true, greater_that_or_equal_to: 0, less_than_or_equal_to: 5}
    validates :address, presence: true

    #SEO
    def to_param
        id.to_s + "-" + title.parameterize
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    def index
        # this is our list page for our reviews
        @price = params[:price]
        @cuisine = params[:cuisine]
        @location = params[:location]

        #start with all the reviews
        @reviews = Review.all

        #filter by price
        if @price.present?
            @reviews = @reviews.where(price: @price)
        end
        
        #filter by cuisine
        if @cuisine.present?
            @reviews = @reviews.where(cuisine: @cuisine)
        end

        #search near the location
        if @location.present?
            @reviews = @reviews.near(@location)
        end


    end


    def new
        # the form for adding a new review
        @review = Review.new
    end

    def create
        #this takes the info from the form and add it to the model
        @review = Review.new(form_params)
        
        # we want to check if the model can be saved
        #  if it is we're going to the home page again
        # if it isnt show the new form
        if @review.save
            redirect_to root_path
        else
            # show the view for new.html.erb
            render "new"
        end

    end

    def show
        #the individual review page
        @review = Review.find(params[:id])
    end   

    def destroy
        #find the indidual review
        @review = Review.find(params[:id])

        #destroy it
        @review.destroy

        #redirect to the home page
        redirect_to root_path
        
    end

    def edit
        #find the individual review (to edit)
        @review = Review.find(params[:id])
    end

    def update
        #find the individual review
        @review = Review.find(params[:id])

        #update with the new info from the form
        if @review.update(form_params)

            #redirect back to updated review
            redirect_to review_path(@review)
        else
           render "edit" 
        end
    end

    def form_params
        params.require(:review).permit(:title, :restaurant, :body, :score, :ambiance, :price, :cuisine, :address)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for :page_title %> - Bien Reviews - The Best Restaurant Reviews in the World</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav>
        <h1>
          <%= link_to root_path do %>
            <%= image_tag "bien-logo.svg" %>
            <% end %>
        </h1>
      </nav>
      <nav>
        <%= link_to "Add a review", new_review_path %>
      </nav>
    </header>  
  
  <main>
  <%= yield %>
  </main>
  
    <footer>
      Copyright 2020 Bien Reviews
    </footer>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for @review  do |f| %>

   <% if @review.errors.any? %>

    <div class="errors">
        
        <% @review.errors.full_messages.each do |message| %>
            <p><%= message %></p>
        <% end %>

    </div>

   <% end %>


    <p>
        <%= f.label :title %>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :restaurant %>
        <%= f.text_field :restaurant %>
    </p>

    <p>
        <%= f.label :address %>
        <%= f.text_field :address %>
    </p>

    <p>
        <%= f.label :cuisine %>
        <%= f.text_field :cuisine %>
    </p>

    <p>
        <%= f.label :body %>
        <%= f.text_area :body %>
    </p>

    <p>
        <%= f.label :score %>
        <%= f.number_field :score %>
    </p>

    <p>
        <%= f.label :price %>
        <%= f.number_field :price %>
    </p>

    <p>
        <%= f.label :ambiance %>
        <%= f.text_field :ambiance %>
    </p>


    
    <%= f.submit "Save Review" %>
<% end %>

app/views/reviews/edit.html.erb
<h3> Edit your review </h3>

<%= render "form" %>

app/views/reviews/index.html.erb
<% content_for :page_title, "Homepage" %>

<nav class="filters">
    <%= link_to "All Restaurants", root_path %>

    <div>
        <%= link_to "$", root_path(price: 1, cuisine: @cuisine, location: @location) %>
        <%= link_to "$$", root_path(price: 2, cuisine: @cuisine, location: @location) %>
        <%= link_to "$$$", root_path(price: 3, cuisine: @cuisine, location: @location) %>
        <%= link_to "$$$$", root_path(price: 4, cuisine: @cuisine, location: @location) %>
        <%= link_to "$$$$$", root_path(price: 5, cuisine: @cuisine, location: @location) %>
    </div>

    <div>
        <%= link_to "Indian", root_path(cuisine: "Indian", price: @price, location: @location) %>
        <%= link_to "Mexican", root_path(cuisine: "Mexican", price: @price, location: @location) %>
        <%= link_to "Italian", root_path(cuisine: "Italian", price: @price, location: @location) %>
    </div>

    <form action="/">
        <input type="text" name="location" 
        placeholder="search location...", value="<%= @location %>">
       
        <input type="hidden" name="price" value="<%= @price %>">
        <input type="hidden" name="cuisine" value="<%= @cuisine %>">
    </form>

</nav>


<% @reviews.each do |review| %>
    <div class="review"> 
        <%= link_to review.title, review_path(review) %>
    </div>
<% end %>

app/views/reviews/new.html.erb
<% content_for :page_title, "Add a new review" %>

<h3> Add your new review </h3>

<%= render "form" %>

app/views/reviews/show.html.erb
<% content_for :page_title, @review.title %>

<h1><%= @review.title %></h1>
<h2><%= @review.restaurant %></h2>

<div class="score">
    <%= @review.score %> / 10
</div>

<% if @review.ambiance.present? %>
    <div class="ambience">
        Ambiance: <%= @review.ambiance %>
    </div>
<% end %>

<% if @review.cuisine.present? %>
    <div class="cuisine">
        Cuisine: <%= @review.cuisine %>
    </div>
<% end %>

<div class="body">
    <%= simple_format @review.body %>
</div>

<% if @review.price.present? %>
    <div class="price">
        Price: <%= @review.price %>
    </div>
<% end %>



<div class="actions">
    <%= link_to "Edit this review", edit_review_path(@review) %>
    <%= link_to "Delete this review", review_path(@review), method: :delete, data: {confirm: "Are you sure?"} %>
</div>